### ISSUE TITLE
Upgrade to Checkstyle 8.21

### ISSUE THREAD

**Issue by snicoll** [spring-io/spring-javaformat#113]
This project uses the latest checkstyle release at that time (8.21). Trying to use `0.0.12` with that version on the `initializr` repository leads to:

```
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution checkstyle-validation of goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:check failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:check: java.lang.VerifyError: class io.spring.javaformat.checkstyle.SpringChecks overrides final method setTabWidth.(I)V
-----------------------------------------------------
realm =    plugin>org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0
```

This can be reproduced by [upgrading the checkstyle version locally](https://github.com/spring-io/initializr/blob/2f50cf1c8ffda7d9b6989e18bfb4a6f8350b9882/pom.xml#L183)

**Comment by wilkinsona** [comment]
It was [added](https://github.com/checkstyle/checkstyle/commit/87a3357169fa8e91ebfae23b4dcccad60943abd7) in 8.19.

**Comment by snicoll** [comment]
Would it be possible to add an integration test in this project or something? The project currently build with that version and I'd expect it to fail.

**Comment by rajadilipkolli** [comment]
Any temporary solution ?

**Comment by wilkinsona** [comment]
You'll have to use Checkstyle 8.18 or earlier for now.

**Comment by wilkinsona** [comment]
8.21 has [changed](https://github.com/checkstyle/checkstyle/issues/6125) how try-with-resources is treated and the formatter and Checkstyle now disagree. The formatter produces this:

```
try (InputStream foo = getInputStreamFor("foo"); InputStream bar = getInputStreamFor("bar")) {
   // …
}
```

Checkstyle reports an error due to multiple statements:

```
[ERROR] src/test/java/org/springframework/boot/configurationmetadata/ConfigurationMetadataRepositoryJsonBuilderTests.java:[66,64] (coding) OneStatementPerLine: Only one statement per line allowed.
[ERROR] src/test/java/org/springframework/boot/configurationmetadata/ConfigurationMetadataRepositoryJsonBuilderTests.java:[79,64] (coding) OneStatementPerLine: Only one statement per line allowed.
[ERROR] src/test/java/org/springframework/boot/configurationmetadata/ConfigurationMetadataRepositoryJsonBuilderTests.java:[92,64] (coding) OneStatementPerLine: Only one statement per line allowed.
[ERROR] src/test/java/org/springframework/boot/configurationmetadata/ConfigurationMetadataRepositoryJsonBuilderTests.java:[138,64] (coding) OneStatementPerLine: Only one statement per line allowed.
```

A change in Checkstyle [is being discussed](https://github.com/checkstyle/checkstyle/issues/6790) and a [PR has been proposed](https://github.com/checkstyle/checkstyle/pull/6832/files). AIUI, the proposed change will mean that an error is no longer reported by default with a property to turn it on.

I'm not sure if we should:

1. wait for a new Checkstyle release
2. change the formatter to split the code onto multiple lines
3. do something else

**Comment by philwebb** [comment]
Changing the formatter is never easy so I'm tempted to fix it at checkstyle. Perhaps we can create our own local copy of that rule until the 8.22 is released.

**Comment by wilkinsona** [comment]
There are only a handful of places in Boot that are affected. See parts of [this commit](https://github.com/wilkinsona/spring-boot/commit/f076ff100e22b2bb66948d9d356a3566664178a6). Another option could be to live with it and avoid having our own interim copy of the rule.

**Comment by philwebb** [comment]
I think I prefer the multiple `try` blocks anyway, they seem a bit easier to read.
