### ISSUE TITLE
Update site always needs two runs to find the latest version

### ISSUE THREAD

**Issue by philwebb** [spring-io/spring-javaformat#125]
I'm not sure why, but the first run of the update site CI step always seems to miss the latest version

**Comment by wilkinsona** [comment]
I checked that 0.0.14 was listed at https://dl.bintray.com/spring/javaformat-eclipse/ after https://ci.spring.io/teams/spring-javaformat/pipelines/spring-javaformat/jobs/publish-eclipse-update-site/builds/38 had completed. I guess that means it's not updating the metadata in content.jar properly?

**Comment by philwebb** [comment]
I wonder if the REST API has got some stale cache. I've updated the script to try the call several times. We'll have to wait until the next release to see if it fixes it.

**Comment by philwebb** [comment]
That didn't fix it, perhaps it actually needs to push the update site as well
