### ISSUE TITLE
Allow configurable line length

### ISSUE THREAD

**Issue by nasreddineskandrani** [spring-io/spring-javaformat#134]
This is following discussion in issue: https://github.com/spring-io/spring-javaformat/issues/100

So the purpose of this issue is to be able to configure the `line length` using an option. Currently it's by default `120`.

**Comment by philwebb** [comment]
I think I'd like to keep the scope of this project as small as possible and have it mainly used to format Spring projects in a consistent way. As such, I think more configuration options isn't something we want to add here.

A general purpose formatter such as https://github.com/jhipster/prettier-java might be a better option for users that want to configure things.
