### ISSUE TITLE
Spring lambda check false positive

### ISSUE THREAD

**Issue by vpavic** [spring-io/spring-javaformat#144]
In Spring Session we have [one test](https://github.com/spring-projects/spring-session/blob/ec82336477a8c396896081bfbf3240f80413730d/spring-session-core/src/test/java/org/springframework/session/web/http/SessionRepositoryFilterTests.java#L1332-L1339) that lambda check reports as false positive:

```java
// We want the filter to work without any dependencies on Spring
@Test
@SuppressWarnings("unused")
void doesNotImplementOrdered() {
	assertThatExceptionOfType(ClassCastException.class).isThrownBy(() -> {
		Ordered o = (Ordered) this.filter;
	});
}
```

This results in:

```
$ ./gradlew checkstyleTest

> Task :spring-session-core:checkstyleTest FAILED
[ant:checkstyle] [ERROR] /home/vpavic/dev/projects/spring-projects/spring-session/spring-session-core/src/test/java/org/springframework/session/web/http/SessionRepositoryFilterTests.java:1335:86: Lambda block is unnecessary. [SpringLambda]

FAILURE: Build failed with an exception.
```

We've had Spring lambda check suppressed for some time now but I wonder if that could be handled somehow by `spring-javaformat` itself?

**Comment by wilkinsona** [comment]
That's quite an unusual lambda expression. It might be possible to detect it by looking more closely at the AST. I think you could work around the problem by using `Ordered.class.cast(this.filter)` instead.

**Comment by vpavic** [comment]
Yes, it is a bit unusual. For the time being I did resort to using `java.lang.Class#cast`. It feels like a better option than suppressing the check for test class with ~1500 LoC.

**Comment by philwebb** [comment]
I can't find an easy way to fix this. Perhaps another way to write that test might be:

```java
assertThat(this.filter).isNotInstanceOf(Ordered.class);
```
