### ISSUE TITLE
format crashes in eclipse 2019-09

### ISSUE THREAD

**Issue by Antonio-Raposo** [spring-io/spring-javaformat#147]
I just installed eclipse 2019-09 and migrated a project from eclipse 2019-03 where spring format works fine. I double checked the installed packages are the same and that the configuration is the same, but on 2019-03 the format comand works fine while on 2019-09 the format command freezes for a while and then crashes with and out of memory error and eclipse asks to restart. Has anyone else experienced the same problem and is there any solution?

**Comment by wilkinsona** [comment]
2019-09 isn't supported yet. See #143.
