### ISSUE TITLE
Consider supporting formatting Groovy code

### ISSUE THREAD

**Issue by marceloverdijk** [spring-io/spring-javaformat#149]
It would be nice if the plugin could support formatting Groovy code as well, e.g. when using Spock for testing. The same indention rules etc could be applied.

**Comment by wilkinsona** [comment]
IMO, this is out of scope of this project which is focused purely on Java code. If there's interest in the Groovy community for a project similar to this but for Groovy, it would be better managed as a separate project.

**Comment by marceloverdijk** [comment]
OK np, I thought it would be easy to re-use the Java formatting rules for Groovy (like indentation, import ordering etc.)

**Comment by wilkinsona** [comment]
Unfortunately not. You need to use Groovy Eclipse's formatter to format Groovy code as the Java formatter does not understand Groovy syntax.

**Comment by marceloverdijk** [comment]
That's a pity, but no problem.
