### ISSUE TITLE
SpringMethodVisibility prevents a private or package-private class from overriding toString()

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/spring-javaformat#153]
```
Method 'toString' in private class should not be public. [SpringMethodVisibility]
```

My usecase was a type that's used as a parameter to a JUnit Jupiter parameterised test. The `toString()` of the type is used as part of the test's method name.

**Comment by philwebb** [comment]
Did you have the `@Override` annotation on the `toString()` method?

**Comment by wilkinsona** [comment]
Ah, thanks Phil. I thought I would have had them as they should be added automatically but I did not. That may be a problem with the Gradle integration, but it's not the problem described here.
