### ISSUE TITLE
SpringLambdaCheck doesnt works in combination with custom header file

### ISSUE THREAD

**Issue by davherrera** [spring-io/spring-javaformat#168]
I'm using a custom header file and recently I've added singleArgumentParentheses with false value.

When I run _mvn validate_ it shows:

> Error:(20,33) java: (extension) SpringLambda: Lambda argument missing parentheses.

After add the parentheses and run _mvn validate_ again it shows:

> Error:(20,35) java: (extension) SpringLambda: Lambda argument has unnecessary parentheses.

**Comment by wilkinsona** [comment]
Thanks for the report. I'm not sure that I understand the relationship between a custom header file and parentheses around lambda arguments. In theory, one should be entirely separate from the other.

Can you please share a minimal project that shows how you've configured things and produces the formatting errors you've described above?

**Comment by davherrera** [comment]
Hi @wilkinsona thanks you for the reply. I've created a demo project, you can find it here: https://github.com/davherrera/spring-javaformat-demo/

In Main class you will find the same lambda expression with and without parentheses.

**Comment by wilkinsona** [comment]
Thanks for the sample. The problem isn't specifically with the custom header, it's with applying both `SpringLambdaCheck` and `SpringChecks`. You can reproduce the problem with the following configuration:

```xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.2//EN"
		"http://www.puppycrawl.com/dtds/configuration_1_2.dtd">
<module name="com.puppycrawl.tools.checkstyle.Checker">
	<!-- Root Checks -->
	<module name="io.spring.javaformat.checkstyle.SpringChecks"/>

	<!-- TreeWalker Checks -->
	<module name="com.puppycrawl.tools.checkstyle.TreeWalker">
		<module name="io.spring.javaformat.checkstyle.check.SpringLambdaCheck">
			<property name="singleArgumentParentheses" value="false"/>
		</module>
	</module>
</module>
```

Applying `SpringChecks` applies all of our code formatting conventions, including `SpringLamdaCheck` configured with `singleArgumentParentheses` set to `false`. The explicit configuration of `SpringLamdaCheck ` but with `singleArgumentParentheses ` set to `true` means that you have the same check configured twice with contradictory configuration.

This project is designed to be opinionated with few configuration options. The intent being to apply consistent formatting without lots of discussion about exactly how code should be formatted. You'll either have to use `SpringChecks` and accept those opinions or configure the individual checks manually to meet your needs.
