### ISSUE TITLE
Automatic publishing to Gradle's Plugin repository isn't working

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/spring-javaformat#173]
The fix for #150 does not seem to have worked. The plugin isn't in the Portal and the attribute isn't set in Bintray.

**Comment by mbhave** [comment]
Probably because the `BINTRAY_USERNAME` and `BINTRAY_API_KEY` are not available as params to the [promote task](https://github.com/spring-io/spring-javaformat/blob/13a2e2e90701ffafbf3668b75e53e3b8e1d07a1b/ci/pipeline.yml#L149).

**Comment by vpavic** [comment]
Any updates on this?
It would be really useful for broader audience if plugin was available from the portal.

**Comment by mbhave** [comment]
I think configuring the bintray credentials should do it. If not, we'll need to investigate further.

**Comment by vpavic** [comment]
Will the publishing be attempted with the `0.0.26` release?
If so, could you assign this issue to the [milestone](https://github.com/spring-io/spring-javaformat/milestone/28) so that it's easier to track?

**Comment by philwebb** [comment]
The attributes were set but it's not in the portal for some reason.

![Screen Shot 2020-12-04 at 5 25 58 PM](https://user-images.githubusercontent.com/519772/101229602-dcd50480-3655-11eb-9c85-69776f9d05a8.png)

**Comment by wilkinsona** [comment]
It's there now: https://plugins.gradle.org/plugin/io.spring.javaformat.
