### ISSUE TITLE
Support IDEA 2020.1

### ISSUE THREAD

**Issue by snsyzf** [spring-io/spring-javaformat#180]
IDEA 2020.1 not support

**Comment by philwebb** [comment]
I've just committed a fix. If you want to try the latest SNAPSHOT it's available at https://repo.spring.io/snapshot/io/spring/javaformat/spring-javaformat-intellij-plugin/0.0.21-SNAPSHOT/spring-javaformat-intellij-plugin-0.0.21-20200410.061412-5.jar
