### ISSUE TITLE
Issue with spring-javaformat-intellij-plugin

### ISSUE THREAD

**Issue by mwesox** [spring-io/spring-javaformat#181]
I've installed the spring-javaformat-intellij-plugin with the latest version 0.0.21 . 
But it seems the plugin has not been activated. E.g. I'm missing the described spring icon in the status bar.  

How can this be debugged? 

Using IntelliJ 2020.1

**Comment by snicoll** [comment]
It's impossible for us to say without more context. How do you configure `spring-javaformat` with the project you're testing it against. Sharing a small project that showcases the problem should help.

**Comment by mwesox** [comment]
@snicoll : 
I'm trying to contribute to spring-cloud-stream-binder-aws-kinesis project. 

Also I'm currently only interested in applying the spring formatting rules on IntelliJ. I thought this plugin helps me (also independently of the underlying project) . Like e.g. the google-format-plugin.

**Comment by snicoll** [comment]
Thank you for trying to contribute to that project.

>  thought this plugin helps me (also independently of the underlying project)

As [described in the README](https://github.com/spring-io/spring-javaformat#intellij-idea), the plugin will be enabled if the plugin is configured for the project.  I don't see the javaformat plugin being configured for it though so you may want to reach out to them

If you are using the project, you should see something like this:

```
[INFO] ----------------< acme:xyz >-----------------
[INFO] Building xyz
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- spring-javaformat-maven-plugin:0.0.20:validate (default) @ xyz ---
[INFO]
[INFO] --- maven-checkstyle-plugin:3.1.1:check (checkstyle-validation) @ xyz ---
[INFO] You have 0 Checkstyle violations.
```

I'll keep the issue open to see if some debugging options would have helped you.

**Comment by mwesox** [comment]
@snicoll : Thx for the info. I think we can close that ticket, as I misunderstood the goal of the plugin ;) ... thx anyway
