### ISSUE TITLE
Use the eclipse preference api instead of writing files

### ISSUE THREAD

**Issue by antonio-vazquez-araujo** [spring-io/spring-javaformat#184]
In the eclipse plugin, the entire mechanism of the `projectsettings ` package is based on directly manipulating the project's preference files.
Wouldn't it be better to use the Eclipse preference api instead? Eclipse does the work internally, more efficiently and easier to maintain. 
Maybe there is an internal reason for this that I can't understand, so I ask this question.
If the problem is the `ProjectProperties getModifiedContent` method, which changes the copyright year, perhaps it would be a better solution to add it as a cleanup in the plugin. I've tried it and it works fine.

Thanks for your good work 
Antonio.

Example using the preference api with the jdt.ui properties:

```
IEclipsePreferences prefs = getNode("org.eclipse.jdt.ui"); 
if (null == prefs) {
    return;
}
if (resetAll) {
    try {
        prefs.clear();
        prefs.flush();
    } catch (BackingStoreException e) {
        e.printStackTrace();
    }
    return;
}
    
Map<String, String> options = new HashMap<>();
try {
    Properties properties = new Properties();
    try (InputStream inputStream = PreferenceSetter.class.getResourceAsStream("org.eclipse.jdt.ui.prefs")) {
        properties.load(inputStream);
        options = (Map) Collections.unmodifiableMap(properties);
    }
} catch (IOException ex) {
    throw new IllegalStateException(ex);
}
options.forEach((key, value) ->prefs.put(key,value));

try {
    prefs.flush();
} catch (org.osgi.service.prefs.BackingStoreException e) {
    e.printStackTrace();
}
```

**Comment by philwebb** [comment]
Thanks for the suggestion. I don't think I ever tried to use the preferences API, I think I just did some copy/paste of some old code that I had. It would be nice to migrate if it offers better performance.

**Comment by philwebb** [comment]
Superseded by #198
