### ISSUE TITLE
Ensure single line of whitespace after header

### ISSUE THREAD

**Issue by philwebb** [spring-io/spring-javaformat#194]

**Comment by manduinca** [comment]
Hi @philwebb. I would like to do this task.

**Comment by philwebb** [comment]
Thanks for the offer @manduinca, but I managed to get to this whilst working on another change.

**Comment by trisberg** [comment]
Hi @philwebb, any thoughts on how we can get this new rule to be applied automatically? Doesn't look like IntelliJ IDEA applies this rule when reformatting code using the `spring-javaformat-intellij-idea-plugin`. So far, we have been forced to manually add this line.
