### ISSUE TITLE
Enable org.eclipse.jdt.core.compiler.problem.deprecationWhenOverridingDeprecatedMethod by default

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/spring-javaformat#196]
The [JLS says the following](https://docs.oracle.com/javase/specs/jls/se8/html/jls-9.html#jls-9.6.4.6):

> A Java compiler must produce a deprecation warning when a type, method, field, or constructor whose declaration is annotated with `@Deprecated` is used (overridden, invoked, or referenced by name) in a construct which is explicitly or implicitly declared, unless:
>
> - The use is within an entity that is itself annotated with the annotation `@Deprecated`; or
> - The use is within an entity that is annotated to suppress the warning with the annotation `@SuppressWarnings("deprecation")`; or
> - The use and declaration are both within the same outermost class.

Spring Java Format currently disables deprecation warnings when overriding deprecated methods. We should enable it so that Eclipse's behaviour is JLS-compliant by default.

**Comment by philwebb** [comment]
Fixed in 021a9624bee9b8b00319594d8fa7305ae46b94f9 but I accidentally referenced the incorrect issue.
