### ISSUE TITLE
Make it easier to exclude more static imports

### ISSUE THREAD

**Issue by philwebb** [spring-io/spring-javaformat#201]
It's hard to add one or two additional exclusions with the current setup.

**Comment by rwinch** [comment]
Was this resolved in https://github.com/spring-io/spring-javaformat/commit/99059ba1b661729b81cfbcd811cb199d2476e25b ?

**Comment by philwebb** [comment]
Ergh, looks like I pushed an accidental commit :(

**Comment by philwebb** [comment]
What a mess :(

I decided to rewrite history so the commit log is clean.
