### ISSUE TITLE
Declare supported IntelliJ IDEA versions in plugin metadata

### ISSUE THREAD

**Issue by snicoll** [spring-io/spring-javaformat#217]
Given that we have to release the plugin quite often as they are breaking change in a lower-level API we have to use, it would be better to actually document the  versions that are compatible.

The plugin metadata can use [build number ranges](https://jetbrains.org/intellij/sdk/docs/basics/getting_started/build_number_ranges.html) for this.

**Comment by snicoll** [comment]
There is actually a `since-build` in there but it is outdated.

**Comment by snicoll** [comment]
I am tempted to go with `<idea-version since-build="201" until-build="202.*"/>` that would enable the plugin for IJ 
`2020.1` and `2020.2`. I've tested on both and it works fine.

The plugin will disable itself when `2020.3` is released but we have a chance to test the EAP and have an extra release beforehand. The other option is to not put a `until-build` and process the feedback if any.

paging @yanncebron for insights

**Comment by YannCebron** [comment]
"it depends" if a plugin uses only small parts/very "stable" part of APIs, then usually omitting `until-build` will work
we recommend using Plugin Verifier to check binary compatibility against all supported versions https://jetbrains.org/intellij/sdk/docs/reference_guide/api_changes_list.html#plugin-verifier

**Comment by philwebb** [comment]
Most of the compatibility issues appear in our `DelegatingCodeStyleManager` class. I guess `com.intellij.psi.codeStyle.CodeStyleManager` is somewhat internal, so it's not that surprising. We only need to override the `reformat...` methods, and those generally don't change much. More often than not it's just methods added in `CodeStyleManager` that we need to add to the delegate.

I seem to remember finding a few other IntelliJ plugins that have similar problems. Perhaps if there was a `DelegatingCodeStyleManager` API already provided by IntelliJ it would help a little?

**Comment by YannCebron** [comment]
Unfortunately there exists no (stable) API yet for delegating code formatting. Please follow https://youtrack.jetbrains.com/issue/IDEA-203568 for progress.

**Comment by krasa** [comment]
Using cglib proxy is much better than extending CodeStyleManager - you will break the IDE pretty much with every API change while the proxy will always work.

https://github.com/krasa/EclipseCodeFormatter/blob/master/src/java/krasa/formatter/plugin/ProxyUtils.java
https://github.com/krasa/EclipseCodeFormatter/blob/master/src/java/krasa/formatter/plugin/ProxyCodeStyleManagerDelegator.java

**Comment by philwebb** [comment]
Thanks for the suggestion @krasa. I've opened #255 to investigate.

**Comment by philwebb** [comment]
With #359 we've switched to use the `DocumentFormattingService` which should be a more stable API.
