### ISSUE TITLE
Import is not optimized

### ISSUE THREAD

**Issue by tonycody** [spring-io/spring-javaformat#221]
spring-javaformat does not optimize import

**Comment by snicoll** [comment]
Thanks for the report but [the README already indicates](https://github.com/spring-io/spring-javaformat#source-formatting) that this isn't in the scope of this project.

**Comment by wilkinsona** [comment]
https://github.com/spring-io/spring-javaformat/issues/197 is also related to this. Specifically [Spotless's import order step](https://github.com/diffplug/spotless/blob/main/lib/src/main/java/com/diffplug/spotless/java/ImportOrderStep.java) may be of use.
