### ISSUE TITLE
Checkstyle conflicts with javaformat

### ISSUE THREAD

**Issue by imyuyu** [spring-io/spring-javaformat#223]
hello!

use `./mvnw spring-javaformat:apply` i get consistent code,but when i use checkstyle,i get the following error:

`Error:(19) java: (whitespace) FileTabCharacter: 文件含有制表符 tab （这只是第一例）。`

And  `Jump to Source` is disabled, which makes it difficult for me to fix the error.
![image](https://user-images.githubusercontent.com/5226695/97800106-84cd6b80-1c6d-11eb-89db-cdd880d6a49d.png)

Is it my configuration problem?

Version:

IntelliJ IDEA:2020.1.1

pom.xml:

```xml
<plugin>
                <groupId>io.spring.javaformat</groupId>
                <artifactId>spring-javaformat-maven-plugin</artifactId>
                <version>0.0.25</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <version>3.1.1</version>
                <dependencies>
                    <dependency>
                        <groupId>com.puppycrawl.tools</groupId>
                        <artifactId>checkstyle</artifactId>
                        <version>8.32</version>
                    </dependency>
                    <dependency>
                        <groupId>io.spring.javaformat</groupId>
                        <artifactId>spring-javaformat-checkstyle</artifactId>
                        <version>0.0.25</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <id>checkstyle-validation</id>
                        <phase>validate</phase>
                        <inherited>true</inherited>
                        <configuration>
                            <configLocation>io/spring/javaformat/checkstyle/checkstyle.xml</configLocation>
                            <includeTestSourceDirectory>true</includeTestSourceDirectory>
                        </configuration>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

**Comment by wilkinsona** [comment]
> Is it my configuration problem?

Your pom looks fine, but I suspect that there is a problem elsewhere with some Checkstyle configuration. It looks as If you're running Checkstyle in your IDE so I would guess that it isn't using the project's Checkstyle configuration and is instead applying some different rules that are configured elsewhere.

**Comment by imyuyu** [comment]
> > Is it my configuration problem?
> 
> Your pom looks fine, but I suspect that there is a problem elsewhere with some Checkstyle configuration. It looks as If you're running Checkstyle in your IDE so I would guess that it isn't using the project's Checkstyle configuration and is instead applying some different rules that are configured elsewhere.

It seems that you are right，I execute it directly using the Maven plugin in the IDE, as shown here:
![image](https://user-images.githubusercontent.com/5226695/97865567-62a71c80-1d45-11eb-925e-4871fffa5810.png)

But I got the same result via command line (`mvn checkstyle:check`) execution.

With your prompt, I looked at the command line message log and found that the rule used is from `sun_checks.xml`
```
[INFO] --- maven-checkstyle-plugin:3.1.1:check (default-cli) @ xxx-framework ---
[INFO] There are 1345 errors reported by Checkstyle 8.32 with sun_checks.xml ruleset.

```

It appears that the following configuration is not in effect：
```
<executions>
				<execution>
					<id>checkstyle-validation</id>
					<phase>validate</phase>
					<inherited>true</inherited>
					<configuration>
						<configLocation>io/spring/javaformat/checkstyle/checkstyle.xml</configLocation>
						<includeTestSourceDirectory>true</includeTestSourceDirectory>
					</configuration>
					<goals>
						<goal>check</goal>
					</goals>
				</execution>
			</executions>
```

Do you have any suggestions?

**Comment by imyuyu** [comment]
I have found that if you use `mvn compile`  or `mvn validate` directly, verification will be performed correctly.

**Comment by wilkinsona** [comment]
That's to be expected with Maven. The `<execution>` above binds the `<check>` goal with specific configuration to the `validate` phase. This is why things work when you run `mvn validate`. When you run `checkstyle:check` you're running the `check` goal with its default configuration which includes `sun_checks.xml`.
