### ISSUE TITLE
Add m2e metadata to jar

### ISSUE THREAD

**Issue by dsyer** [spring-io/spring-javaformat#224]
I don't see any lifecycle mapping metadata in this plugin (unlike, for instance, the Spring Boot plugin). Could be a nice thing for users not to have to suppress locally. From the Spring Boot plugin we have:

```xml
<lifecycleMappingMetadata>
	<pluginExecutions>
		<pluginExecution>
			<pluginExecutionFilter>
				<goals>
					<goal>build-info</goal>
				</goals>
			</pluginExecutionFilter>
			<action>
				<execute>
					<runOnIncremental>true</runOnIncremental>
					<runOnConfiguration>false</runOnConfiguration>
				</execute>
			</action>
		</pluginExecution>
	</pluginExecutions>
</lifecycleMappingMetadata>
```

at `META-INF/m2e/lifecycle-mapping-metadata.xml`.

See https://github.com/spring-projects/spring-petclinic/issues/651

**Comment by wilkinsona** [comment]
The metadata is already [available in the Eclipse plugin](https://github.com/spring-io/spring-javaformat/blob/310b37f72103794ce359cbee312ee0cb56a38b07/spring-javaformat-eclipse/io.spring.javaformat.eclipse/lifecycle-mapping-metadata.xml). It registers a configurator with M2E to set everything up. I don't think we can have two lots of metadata as they'll clash.

**Comment by dsyer** [comment]
Does the user have to do something explicit to register the configuration? The OP in the PetClinic issue was still seeing errors in the pom.

**Comment by wilkinsona** [comment]
Perhaps they don't have the Eclipse plugin installed? There are some [instructions on installing it](https://github.com/spring-io/spring-javaformat#eclipse) in the README.
