### ISSUE TITLE
Upgrade to Eclipse 2020-09

### ISSUE THREAD

**Issue by Antonio-Raposo** [spring-io/spring-javaformat#225]
I have started getting this message every time I save a file in my eclipse. Also noticed that it does not format source code anymore, I have to do it by hand. Suppose it has something to do with the last actualization. Eclipse reports the Java IDE as beeing version 4.17.0.20200910-1200

A save participant caused problems.
  The save participant 'Code Clean Up' caused an exception: java.lang.IndexOutOfBoundsException: Index 1849 out of bounds for length 1849. See the error log for details.

**Comment by wilkinsona** [comment]
Thanks for the report. The Eclipse plugin does not yet support Eclipse 2020-09. We can use this issue to perform that upgrade.

**Comment by Antonio-Raposo** [comment]
I supposed it had something to do with the eclipse actualization and I was right... If you need any more data please ask and I will try to find logs or wathever may help.
