### ISSUE TITLE
Publish Gradle plugin to Gradle's plugin repository

### ISSUE THREAD

**Issue by vpavic** [spring-io/spring-javaformat#251]
I'm opening a new issue to track this effort, since previous attempts to do so have been unsuccessful.

See #150 and #173.

**Comment by wilkinsona** [comment]
0.0.26 made it to the Portal: https://plugins.gradle.org/plugin/io.spring.javaformat.

**Comment by vpavic** [comment]
That's really great news! :tada:

Sorry for the noise in that case, I checked a few times after `0.0.26` was released but it wasn't there.
