### ISSUE TITLE
SaveActions failed with Eclipse 2020-06 & 2020-09

### ISSUE THREAD

**Issue by joteri** [spring-io/spring-javaformat#253]
Hi, I was hoping you could give me a hand with this error I'm having when I save certain classes and the save actions apply.

It doesn't happen with just any class, only with some classes. And i've found that commenting every switch case out and leaving just the default one seems to prevent the crash.

I have tried to change the implementation used by the formatter to "Eclipse [Built-in]" instead of "Spring" and I have not experienced the same problem again.

I use Eclipse 2020-06 and version 0.0.26 of spring-javaformat. Tried to test with Eclipse 2020-09 but the problem persists.

https://github.com/joteri/spring-javaformat-issue-files -> The link to the repository with the class causing the error, the stacktrace and the error window that appears.

Do you know what the error may be? Thanks in advance, a greeting.

**Comment by philwebb** [comment]
Could you try release 0.0.27 with Eclipse 2020-12 and let me know if the problem is still there? I couldn't get your sample file to fail with that release.

**Comment by joteri** [comment]
I did the same test with the 0.0.27 and eclipse 2020-12 and everything worked fine.

I have tried this last release with the 2020-06 and 2020-09 but it results in memory problems. 

I have no problem upgrading to the latest version of Eclipse but I was hoping you could answer the following question, What is the reason for the lack of compatibility with previous platforms? Is it due to its complexity or is it due to ruptured changes in the Eclipse API?

Thanks for your help.

**Comment by philwebb** [comment]
I'm honestly not sure why things sometimes break during an upgrade. I wanted to look into it a little more to see if we could stop it happening. Unfortunately, I haven't had the time.

**Comment by wilkinsona** [comment]
#288 has hopefully taken care of this one.
