### ISSUE TITLE
Consider to make available the Eclipse Plugin through Eclipse Marketplace

### ISSUE THREAD

**Issue by manueljordan** [spring-io/spring-javaformat#257]
In the [Eclipse](https://github.com/spring-io/spring-javaformat#eclipse) section appears the following:

> To install the plugin use the io.spring.javaformat.eclipse.site zip file. You can download the latest version from repo.spring.io or use the update site.

So for installation purposes: Would you consider to make available that plugin through Eclipse Marketplace? It to save it how favorites in our Eclipse accounts to be reused in new installations on STS/Eclipse for other machines.

Thanks for your understanding

**Comment by philwebb** [comment]
Thanks for the suggestion, but I'm not keen to add it to the market place. I'm happy that people find the project useful, but it's mainly intended for Spring projects to use and I don't want the extra maintenance burden that goes along with advertising it too widely.
