### ISSUE TITLE
Migration of the update site due to the termination of Bintray's service.

### ISSUE THREAD

**Issue by k163377** [spring-io/spring-javaformat#263]
I have a question about the migration of the `update site` due to the termination of the `Bintray` service.

Currently, an `update site` for `Eclipse` is available at `Bintray`.
https://github.com/spring-io/spring-javaformat#eclipse
https://dl.bintray.com/spring/javaformat-eclipse/

On the other hand, the service of `Bintray` has been announced to be terminated at the end of April, and the following page shows a warning.
https://bintray.com/spring/javaformat-eclipse/update-site

Are there any plans to move the `update site` to another location?

Thank you.

**Comment by philwebb** [comment]
Yes, we need to find a new home for the update site. I plan to look at this next time we cut a release.

**Comment by wilkinsona** [comment]
Perhaps we could use repo.spring.io, either with a P2 repository or a generic repository?

**Comment by k163377** [comment]
@philwebb Thank you for responding!
