### ISSUE TITLE
Run only on staged files

### ISSUE THREAD

**Issue by Kjens93** [spring-io/spring-javaformat#268]
Is there a way to run the formatter only on staged files? I'm using the Maven plugin with Git, and I would like to configure this to run as a pre-commit hook, but only on staged files or chunks. The staged files/chunks would need to be re-added to the git index after formatting.

**Comment by philwebb** [comment]
I'm afraid not and I don't think we should tie the maven/gradle plugins aware of git. You could probably write your own Maven Plugin or CLI app and call [`FileFormatter`](https://github.com/spring-io/spring-javaformat/blob/51cde82af33d3e4b2b195472fde7b8ddf37c4730/spring-javaformat/spring-javaformat-formatter/src/main/java/io/spring/javaformat/formatter/FileFormatter.java). Take a look at [`FormatMojo`](https://github.com/spring-io/spring-javaformat/blob/51cde82af33d3e4b2b195472fde7b8ddf37c4730/spring-javaformat-maven/spring-javaformat-maven-plugin/src/main/java/io/spring/format/maven/FormatMojo.java#L113) for inspiration.
