### ISSUE TITLE
Warn about unused declared thrown exceptions

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/spring-javaformat#273]
We have numerous places in Boot where we've declared that an exception is thrown when it isn't or when the exception is a `RuntimeException` so it doesn't need to be declared. There's [a PR that removes them](https://github.com/spring-projects/spring-boot/pull/26441) which I am in favour of. I think it would also be nice to try and stop them reappearing. To that end, we could change the Eclipse JDT core preferences. Instead of the following:

https://github.com/spring-io/spring-javaformat/blob/c8835c892f19877a98c6c62679896670566b8bec/spring-javaformat-eclipse/io.spring.javaformat.eclipse/src/io/spring/javaformat/eclipse/projectsettings/org.eclipse.jdt.core.prefs#L91-L94

We'd use the following:

```
org.eclipse.jdt.core.compiler.problem.unusedDeclaredThrownException=warning
org.eclipse.jdt.core.compiler.problem.unusedDeclaredThrownExceptionExemptExceptionAndThrowable=disabled
org.eclipse.jdt.core.compiler.problem.unusedDeclaredThrownExceptionIncludeDocCommentReference=disabled
org.eclipse.jdt.core.compiler.problem.unusedDeclaredThrownExceptionWhenOverriding=enabled
```

The changes above will result in warnings being generated for checked exceptions that are unnecessarily declared as thrown. It won't help with unchecked exceptions.

**Comment by wilkinsona** [comment]
Thinking some more, we may want to leave the following two settings unchanged:

```
org.eclipse.jdt.core.compiler.problem.unusedDeclaredThrownExceptionIncludeDocCommentReference=enabled
org.eclipse.jdt.core.compiler.problem.unusedDeclaredThrownExceptionWhenOverriding=disabled
```

This will allow exception to be declared thrown if it's mentioned in the javadoc or if it comes from the signature of a method that's being overridden.

**Comment by weixsun** [comment]
> This will allow an exception to be declared thrown if it's mentioned in the javadoc or if it comes from the signature of a method that's being overridden.

@wilkinsona yes, when I was erasing an exception that was never thrown, I deliberately kept the case you mentioned.

e.g.: 

```java
class TestFilter implements Filter {
	@Override
	public void doFilter(ServletRequest request, ServletResponse response,
			FilterChain chain) throws IOException, ServletException {
		// do something
	}
}
```

`IOException` and `ServletException` should not be erased even if never thrown.
