### ISSUE TITLE
Don't set jdt compiler/complience versions in Eclipse plugin

### ISSUE THREAD

**Issue by philwebb** [spring-io/spring-javaformat#278]
The following settings don't seem like our responsibility.

```
org.eclipse.jdt.core.compiler.codegen.targetPlatform=1.8
org.eclipse.jdt.core.compiler.compliance=1.8
org.eclipse.jdt.core.compiler.source=1.8
```

**Comment by quaff** [comment]
Yes, please remove them from `eclipse-code-formatter.xml`, gradle plugin will generate rightful `org.eclipse.jdt.launching.JRE_CONTAINER` in `.classpath`.
