### ISSUE TITLE
Links to distribution artifacts on repo.spring.io are not working anymore

### ISSUE THREAD

**Issue by jinghongjiang** [spring-io/spring-javaformat#279]
https://repo.spring.io/ui/native/release/io/spring/javaformat/spring-javaformat-intellij-idea-plugin/0.0.28/

```json
{
  "errors": [
    {
      "status": 404,
      "message": "Not Found"
    }
  ]
}
```

**Comment by snicoll** [comment]
@jinghongjiang thanks for the report. This is due to an update of our artifactory instance, you can find the bits that you need [on Maven Central](https://repo1.maven.org/maven2/io/spring/javaformat/spring-javaformat-intellij-idea-plugin/0.0.28/) as well. I will update the links.
