### ISSUE TITLE
Allow source folders to be excluded

### ISSUE THREAD

**Issue by philwebb** [spring-io/spring-javaformat#28]
Generates source files such as `target/generated-sources/plugin/org/springframework/boot/maven/HelpMojo.java` cannot easily be excluded currently because the exclude pattern only matches against `org/springframework/boot/maven/HelpMojo.java`. We need an easy way to exclude an entire folder.

**Comment by snicoll** [comment]
Perhaps we should exclude generated sources instead? There is probably a way to detect that

**Comment by philwebb** [comment]
Looks like `generated-sources` is [usually used](https://github.com/antlr/antlr4/blob/8005cfd090d709856a42d78547aec75a4a7bdbc1/antlr4-maven-plugin/src/main/java/org/antlr/mojo/antlr4/Antlr4Mojo.java#L169). Seems to just be an agreed convention rather than a hard rule or something that we can discover. It's still probably good enough.
