### ISSUE TITLE
IndexOutOfBoundsException on save still exists

### ISSUE THREAD

**Issue by quaff** [spring-io/spring-javaformat#283]
eclipse error [log.txt](https://github.com/spring-io/spring-javaformat/files/7142290/log.txt)

eclipse:
Version: 2021-06 (4.20.0)
Build id: 20210612-2011

Spring Java Format: 0.0.28

------------------------------------------------------------
Gradle 7.2
------------------------------------------------------------

Build time:   2021-08-17 09:59:03 UTC
Revision:     a773786b58bb28710e3dc96c4d1a7063628952ad

Kotlin:       1.5.21
Groovy:       3.0.8
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.12 (Homebrew 11.0.12+0)
OS:           Mac OS X 11.5.2 x86_64

**Comment by wilkinsona** [comment]
Eclipse 2021-06 is not yet supported. See https://github.com/spring-io/spring-javaformat/issues/277.
