### ISSUE TITLE
How to suppress the "this" keyword check

### ISSUE THREAD

**Issue by davesahil** [spring-io/spring-javaformat#304]
Hello,

Is there a way to suppress the "this" keyword check for instance variables? Is the "SpringNoThisCheck" meant for this purpose or something else?

Thanks,
Sahil

**Comment by wilkinsona** [comment]
I guess you're referring to the check that requires the use of `this`:

https://github.com/spring-io/spring-javaformat/blob/84dcece4f3dd141d4acadef84627cddb3db71289/spring-javaformat/spring-javaformat-checkstyle/src/main/resources/io/spring/javaformat/checkstyle/spring-checkstyle.xml#L66

The README [describes how to exclude specific checks](https://github.com/spring-io/spring-javaformat#excluding-specific-checks).
