### ISSUE TITLE
Since version 0.0.30, the plugin is not useable with java 8. 

### ISSUE THREAD

**Issue by kvmw** [spring-io/spring-javaformat#314]
Since version 0.0.30,  using the (gradle) plugin in projects with java 8 support fails with following error:
```
* What went wrong:
Execution failed for task ':my-module:checkFormatMain'.
> io/spring/javaformat/eclipse/jdt/jdk11/internal/formatter/DefaultCodeFormatter has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

I was wondering if this is a bug or it was a decision by the team to stop supporting java 8.

**Comment by wilkinsona** [comment]
There's an extra step that's now required to use Java 8 due to the latest Eclipse formatters requiring Java 11. Please see [the README](https://github.com/spring-io/spring-javaformat#java-8-support) for details.
