### ISSUE TITLE
Add JavadocPackageCheck to the default Spring checks

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/spring-javaformat#328]

**Comment by spencergibb** [comment]
Can it be optional?

**Comment by philwebb** [comment]
It should be easy enough to exclude

**Comment by wilkinsona** [comment]
The check can be excluded completely using the `excludes` property when declaring the `SpringChecks` module:

```xml
<module name="io.spring.javaformat.checkstyle.SpringChecks">
    <property name="excludes" value="com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocPackageCheck" />
</module>
```

Alternatively, `JavadocPackage` can be suppressed in `checkstyle-suppressions.xml` for specific files where the check is unwanted.
