### ISSUE TITLE
Provide an indication that the IDEA formatter is active

### ISSUE THREAD

**Issue by jtammen** [spring-io/spring-javaformat#34]
Hey,

I am using IntelliJ IDEA Ultimate 2018.1.4.

I have installed "spring-javaformat" plugin Version 1.0.

I added this to my parent `pom.xm` under `build.plugins`:

```
<plugin>
  <groupId>io.spring.javaformat</groupId>
  <artifactId>spring-javaformat-maven-plugin</artifactId>
  <version>0.0.3</version>
</plugin>
```

How do I know if the custom formatter is enabled? I do not see anything related to it unter `Settings > Editor > Code Style > Java`. It still says "Scheme: Default IDE".

Thanks!

**Comment by philwebb** [comment]
It would be nice to provide some indicator that the formatter is active. Currently there are a bunch of monitors that try to detect from the project configuration when to active the formatter. In your case the [MavenMonitor](https://github.com/spring-io/spring-javaformat/blob/1f17a2af7074e8b96a25d85daeed973432befc20/spring-javaformat-intellij/spring-javaformat-intellij-plugin/src/main/java/io/spring/format/formatter/intellij/codestyle/monitor/MavenMonitor.java) should see the plugin declaration in your POM and active the formatter.

If you apply code reformatting you should see things change. I usually test by picking a file with a couple of private variable and check that whitespace appears between them.

I'll re-purpose this issue to see if we can add an enhancement to make it more obvious that the formatter is active.

**Comment by philwebb** [comment]
@snicoll Are you aware of any other plugins that do this? Is there a standard way to show the active formatter?

**Comment by snicoll** [comment]
I am not aware of anything and was wondering the same thing. I've had a chat with @yanncebron about some related details so I'll bug him again when I get a chance.
