### ISSUE TITLE
The idea plugin has some interfaces that are not implemented

### ISSUE THREAD

**Issue by auto-generated** [spring-io/spring-javaformat#345]
Method with PsiElement is not implemented，If the following code formatting is called in the plug-in developed by yourself, it does not work

```java
CodeStyleManager.getInstance(xxx).reformat(xxx);
```
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/32949827/197341327-f4ae853e-5337-4ab0-8eba-f3715688b676.png">

**Comment by philwebb** [comment]
With #359 we've switched to use the `DocumentFormattingService` which I hope will fix these kinds of issues. If you can replicate the problem after v0.0.36 is released, please re-open this issue.
