### ISSUE TITLE
Formatting java record with generics adds a whitespace before a bracket

### ISSUE THREAD

**Issue by lazystone** [spring-io/spring-javaformat#348]
Spring format adds a white space between `>` and `(`:

```java
private record LookupResult<T> (T match, boolean hasMore) {
	}
```

And then checkstyle fails with
```
'(' is preceded with whitespace.
```

**Comment by wilkinsona** [comment]
This behavior is controlled by `org.eclipse.jdt.core.formatter.insert_space_after_closing_angle_bracket_in_type_parameters`. To avoid adding the whitespace we should set it to `do not insert`.
