### ISSUE TITLE
Add options to skip Maven goals from command line

### ISSUE THREAD

**Issue by lfvjimisola** [spring-io/spring-javaformat#360]
We would like to default to always applying formatting rules and then validating, i.e.

```xml
    <build>
        <plugins>
            <plugin>
                <groupId>io.spring.javaformat</groupId>
                <artifactId>spring-javaformat-maven-plugin</artifactId>
                <version>0.0.35</version>
                <executions>
                    <execution>
                        <phase>validate</phase>
                        <inherited>true</inherited>
                        <goals>
                            <goal>apply</goal>
                            <goal>validate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
```

However, in our pipelines we then need to skip the apply goal to make sure that the code is actually correctly validated.

We would like to avoid using profiles and just add command line parameter similar to `-Dmaven.test.skip`, e.g.

* `-Dspring-javaformat.apply.skip`
* `-Dspring-javaformat.validate.skip`

I've checked issues and code and could not see that it has been brought up or is implemented.

**Comment by philwebb** [comment]
This should be relatively easy to implement. Something similar to https://github.com/spring-projects/spring-boot/blob/7377d85096ed943a06341d94e43a1208238850b5/spring-boot-project/spring-boot-tools/spring-boot-maven-plugin/src/main/java/org/springframework/boot/maven/StopMojo.java#L67-L68

**Comment by jimisola** [comment]
> This should be relatively easy to implement. Something similar to https://github.com/spring-projects/spring-boot/blob/7377d85096ed943a06341d94e43a1208238850b5/spring-boot-project/spring-boot-tools/spring-boot-maven-plugin/src/main/java/org/springframework/boot/maven/StopMojo.java#L67-L68

Yes, exactly. Or as here ;):

https://github.com/spring-io/spring-javaformat/blob/main/spring-javaformat-maven/spring-javaformat-maven-plugin/src/main/java/io/spring/format/maven/ValidateMojo.java#L43

I missed that there was a skip in ValidateMojo ("spring-javaformat.skip). A bit unfortunate that is using a common property name.

I would have preferred to use `spring-javaformat.skip` to skip **both** validate and apply goals. Changing it now would be a breaking change.

Perhaps, adding:

* spring-javaformat.apply.skip: skip apply goal
* spring-javaformat.validate.skip: skip validate goal

and deprecating:

* spring-javaformat.skip: to allow to change it's behavior or using `spring-javaformat.all.skip`

**Comment by lfvjimisola** [comment]
That was fast. Thanks @philwebb

**Comment by lfvjimisola** [comment]
@philwebb Are there any tests for this? I can't seem to get it work unless I'm making a silly mistake.
Can you please confirm on your end?

**Comment by lfvjimisola** [comment]
MRE: [test.zip](https://github.com/spring-io/spring-javaformat/files/10811723/test.zip)

```
u30576@DCL0004:~/test/test$mvn validate -Dspring-javaformat.apply.skip=true
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------------------< test:test >------------------------------
[INFO] Building test 0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- spring-javaformat-maven-plugin:0.0.38:apply (default) @ test ---
[INFO] 
[INFO] --- spring-javaformat-maven-plugin:0.0.38:validate (default) @ test ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.280 s
[INFO] Finished at: 2023-02-23T09:46:23+01:00
[INFO] ------------------------------------------------------------------------

```

**Comment by lfvjimisola** [comment]
Ok. None of the three (3) skip options seem to work:

* -Dspring-javaformat.skip=true
* -Dspring-javaformat.apply.skip=true
* -Dspring-javaformat.validate.skip=true
