### ISSUE TITLE
Allow more configuration options for indentation-style (tabs and spaces)

### ISSUE THREAD

**Issue by lfvjimisola** [spring-io/spring-javaformat#362]
The documentation states that one can change indentation style (tabs or spaces) by placing `.springjavaformatconfig` to the root of your project with the following content:

```
indentation-style=spaces
```

However, it would be preferably to have a centralized way of configuring it. Adding a file for just one setting really clutters the repo (and there are others libraries/tools that do the same).

Preferably, for us would be to be able to set it without adding another file, i.e. with/for Maven in POM.xml and as a setting directly in VS Code.

I understand that this might not get picked up by the other Gradle, Eclipse, IntelliJ and VS Code (+ Maven = Big 5). 

Perhaps, it increases the risk since it's not a Single-Source of Truth setting anymore.

Essentially, this issue is about avoiding having to add yet another file to the repo (reduce clutter) but it might not be possible.

**Comment by philwebb** [comment]
I'm afraid I've tried to do this before for line widths and failed to find a way that works with all plugins and all IDEs. See https://github.com/spring-io/spring-javaformat/issues/100#issuecomment-486328273 for background. I don't think we can justify the investment needed for this feature, especially as the Spring team generally prefer tabs.
