### ISSUE TITLE
Missing space between closing generic bracket and extends keyword

### ISSUE THREAD

**Issue by izeye** [spring-io/spring-javaformat#363]
The formatter removes spaces between class' closing generic bracket and `extends` keyword since 0.0.36.

See https://github.com/micrometer-metrics/micrometer/pull/3662/files#diff-82b97272c72542a13d735cc85463667675ff2f18c4d8dfd9ff4e2753b2ca6262R29 for example.

**Comment by philwebb** [comment]
dag nam it!

**Comment by philwebb** [comment]
It turns out that #348 needs to be selective about when `insert_space_after_closing_angle_bracket_in_type_parameters` is set to `insert`/`do not insert`.

**Comment by philwebb** [comment]
I'm seeing the same issue with 0.0.37 formatting Spring Boot 3.0.x

**Comment by philwebb** [comment]
```
public class UnresolvedGenericProperties<B extends Number, C>extends AbstractGenericProperties<String, B, C> {

}
```

**Comment by philwebb** [comment]
👀  https://github.com/eclipse-jdt/eclipse.jdt.core/commit/f2bcccf568ef227b0651056c241727244f4b8334
