### ISSUE TITLE
Property for skipping formatting in the README doesn't match the property in the code

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/spring-javaformat#365]
The README mentions `-Dspring-javaformat.apply.skip=true` but the code looks for `-Dspring-javaformat.format.skip=true`.

**Comment by lfvjimisola** [comment]
None of the three (3) skip options seem to work:

* -Dspring-javaformat.skip=true
* -Dspring-javaformat.apply.skip=true
* -Dspring-javaformat.validate.skip=true

**Comment by lfvjimisola** [comment]
Looking at https://github.com/spring-io/spring-javaformat/blob/main/spring-javaformat-maven/spring-javaformat-maven-plugin/src/main/java/io/spring/format/maven/ApplyMojo.java#L43 which used `spring-javaformat.format.skip` but that does not work either with my [MRE](https://github.com/spring-io/spring-javaformat/issues/360#issuecomment-1441386938).

**Comment by wilkinsona** [comment]
I think you may be misinterpreting Maven's output. When a goal is skipped, Maven will still call it and that fact that it has been called will appear in Maven's output. It is up to the goal to perform no processing when skipped. The apply and validate goals output some debug logging indicating that they have been skipped. For example:

```
$ mvn validate -X -Dspring-javaformat.validate.skip=true
…
[INFO] --- spring-javaformat-maven-plugin:0.0.38:validate (default) @ test ---
[DEBUG] Configuring mojo io.spring.javaformat:spring-javaformat-maven-plugin:0.0.38:validate from plugin realm ClassRealm[plugin>io.spring.javaformat:spring-javaformat-maven-plugin:0.0.38, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@531d72ca]
[DEBUG] Configuring mojo 'io.spring.javaformat:spring-javaformat-maven-plugin:0.0.38:validate' with basic configurator -->
[DEBUG]   (f) encoding = UTF-8
[DEBUG]   (f) excludes = []
[DEBUG]   (f) includeGeneratedSource = false
[DEBUG]   (f) includes = []
[DEBUG]   (f) project = MavenProject: test:test:0.1-SNAPSHOT @ /Users/awilkinson/Downloads/test-4/pom.xml
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@6d467c87
[DEBUG]   (f) skip = true
[DEBUG]   (f) sourceDirectories = [/Users/awilkinson/Downloads/test-4/src/main/java]
[DEBUG]   (f) testSourceDirectories = [/Users/awilkinson/Downloads/test-4/src/test/java]
[DEBUG] -- end configuration --
[DEBUG] skipping format validate as per configuration.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.022 s
[INFO] Finished at: 2023-02-23T09:45:51Z
[INFO] ------------------------------------------------------------------------
```

**Comment by wilkinsona** [comment]
We should consider logging the skip message at info level. That's what [Surefire does](https://github.com/apache/maven-surefire/blob/208eae24bd8068d90078362f57fe2246ba1b2107/maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java#L1079) for example.

**Comment by lfvjimisola** [comment]
@wilkinsona Do you get `[DEBUG]   (f) skip = true` when you  try to skip apply?

That is, `mvn validate -X -Dspring-javaformat.apply.skip=true`

I don't get  `[DEBUG]   (f) skip = true`

for

* -Dspring-javaformat.skip=true
* -Dspring-javaformat.apply.skip=true

only for

* -Dspring-javaformat.validate.skip=true

**Comment by lfvjimisola** [comment]
> We should consider logging the skip message at info level. That's what [Surefire does](https://github.com/apache/maven-surefire/blob/208eae24bd8068d90078362f57fe2246ba1b2107/maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java#L1079) for example.

Yes, agreed.

**Comment by wilkinsona** [comment]
As I said in https://github.com/spring-io/spring-javaformat/issues/360#issuecomment-1441413700, you need to use `-Dspring-javaformat.format.skip=true`. You will then see `skipping format apply as per configuration` logged at debug level. 

You'll see both `skipping format apply as per configuration` and `skipping format validate as per configuration` logged when using `-Dspring-javaformat.skip=true`. You won't see `[DEBUG]   (f) skip = true` when setting `spring-javaformat.skip` as that's showing the value of the parameter to which `spring-javaformat.format.skip` and `spring-javaformat.validate.skip` are mapped.

**Comment by jimisola** [comment]
Ok. Got a bit confused there. So, `-Dspring-javaformat.format.skip=true` will _only_ skip `apply? ?

**Comment by wilkinsona** [comment]
Yes. `spring-javaformat.format.skip` skips apply, `spring-javaformat.validate.skip` skips validation, and `spring-javaformat.skip` skips both. Other than the mistake with the name of the property to skip apply, this is described in the README:

> You can use `-Dspring-javaformat.validate.skip=true` or `-Dspring-javaformat.apply.skip=true` command line arguments to temporarily skip the validation or format goals. If you want to skip both, you can use `-Dspring-javaformat.skip=true`.

**Comment by lfvjimisola** [comment]
@wilkinsona Sorry for the confusion and for you having the explain several times. Have a very hectic week and it became now that I rushed things. I totally missed that `apply` was replaced with `format` although I did a cut-n-paste from your text.

I would +1 to allow `spring-javaformat.apply.skip` as it makes sense to be consistent with the naming of skip variables and maven goal.

**Comment by philwebb** [comment]
I messed up the property name in the code.
