### ISSUE TITLE
Option to target formatting to specific files

### ISSUE THREAD

**Issue by mmadson** [spring-io/spring-javaformat#372]
Would like similar capability as:

https://github.com/diffplug/spotless/tree/main/plugin-maven#can-i-apply-spotless-to-specific-files

Thanks.

**Comment by philwebb** [comment]
Thanks for the suggestion but we don't have a great deal of time to spend on this project and we don't have a need for such a feature in Spring's own projects, I don't think we'll be able to do this.

I'm also keen to keep the project as simple as possible without adding too many configuration options.

Thanks anyway for the suggestion.

**Comment by wilkinsona** [comment]
@mmadson You may be interested to know that this capability is already available when using Gradle. It's built into [Gradle's `SourceTask`](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/SourceTask.html) that the formatting tasks extend.
