### ISSUE TITLE
Camel DSL routes with spring javaformat

### ISSUE THREAD

**Issue by lfvdaniel** [spring-io/spring-javaformat#386]
Hi,

I have a question about how to make spring javaformat to play nice with Apache Camel DSL.

Our team uses the project and for the most part it works fine, but when we do Apache Camel Routes with Camel DSL the result is not so good.

Below is an example of how I would like it to be formated:

```
from("direct:start")
    .choice()
        .when(body().contains("Camel"))
            .loadBalance().roundRobin()
                .to("mock:foo")
                .to("mock:bar")
    .endChoice()
    .otherwise()
        .to("mock:result");
```

After saving it looks like this.

```
from("direct:start").choice()
	.when(body().contains("Camel"))
	.loadBalance()
	.roundRobin()
	.to("mock:foo")
	.to("mock:bar")
	.endChoice()
	.otherwise()
	.to("mock:result");
```
How can this be fixed?
Is there a way to select parts of the code not to format?
Other suggestions?

BR
/Daniel

**Comment by snicoll** [comment]
This is covered in the readme: https://github.com/spring-io/spring-javaformat
