### ISSUE TITLE
Update gradle example to use `plugins` block.

### ISSUE THREAD

**Issue by junghoon-vans** [spring-io/spring-javaformat#394]
As currently written in the example code for gradle, It is the [legacy way](https://docs.gradle.org/current/userguide/plugins.html#sec:script_plugins) to set up plugins.

If we were to change to code that uses the plugins block, it would be a bit more user-friendly, 
nd it would be a simple change to make by reducing the number of lines in the code example.

## AS-IS

```groovy
buildscript {
	repositories {
		mavenLocal()
		mavenCentral()
	}
	dependencies {
		classpath("io.spring.javaformat:spring-javaformat-gradle-plugin:0.0.40")
	}
}

apply plugin: 'io.spring.javaformat'
```

## TO-BE

```groovy
plugins {
	 id 'io.spring.javaformat' version '0.0.40'
}
```

**Comment by wilkinsona** [comment]
Thanks for the suggestion. Until the plugin is published to Gradle's plugin portal (https://github.com/spring-io/spring-javaformat/issues/309), this change as proposed will break people's builds as they won't be able to resolve the plugin. It could be addressed by also configuring the plugin repositories in `settings.gradle` to add `mavenCentral()`. I'm not totally convinced it's worth it though. WDYT, @philwebb?

**Comment by philwebb** [comment]
Given that the project is mainly for ourselves, I don't think we should make the change. We can add a note to #309 to update the docs if we get publishing working.
