### ISSUE TITLE
Update README: solution for excluding a package from being checked doesn't work

### ISSUE THREAD

**Issue by brendonmiranda** [spring-io/spring-javaformat#405]
The documentation indicates a way for excluding packages from being checked that doesn't work (spotted on gradle 7.5):

> In case you want to exclude a package from being checked, for example if you generate sources, you can do this by adding following configuration:
```
tasks.withType(io.spring.javaformat.gradle.tasks.CheckFormat) {
    exclude "package/to/exclude"
}
```

When trying to find a solution to exclude generated source packages I was able to find one in the spring-boot's build.gradle: https://github.com/spring-projects/spring-boot/blob/107dc5338ba8aff35e2ecb8f6872e23f4ab9e979/spring-boot-project/spring-boot/build.gradle#L160C1-L166C2

The documentation solution can be updated to the following:
```java
tasks.withType(io.spring.javaformat.gradle.tasks.CheckFormat) {
	def generatedSources = fileTree("package/to/exclude")
	exclude { candidate -> generatedSources.contains(candidate.file) }
}
```

I'd love to open a PR if this change is agreed. Thanks.

**Comment by wilkinsona** [comment]
It works for me as shown in the README. Can you please share a minimal example that shows it not working?

**Comment by mborko** [comment]
I'm sorry, but have I missed the configuration for a maven build? The following config doesn't work for me:

```xml
            <plugin>
                <groupId>io.spring.javaformat</groupId>
                <artifactId>spring-javaformat-maven-plugin</artifactId>
                <version>0.0.42</version>
                <executions>
                    <execution>
                        <phase>validate</phase>
                        <inherited>true</inherited>
                        <configuration>
                            <excludes>
                                <exclude>x0Assertion/oasisNamesTcSAML1</exclude>
                            </excludes>
                        </configuration>
                        <goals>
                            <goal>validate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

So before posting, I checked your Code twice and found the `@Parameter(property = "spring-javaformat.excludes")` and this was very helpful. After setting the list of packages in the properties section of my pom.xml, it worked!

```xml
    <properties>
        <!-- Spring-javaformat global settings -->
        <spring-javaformat.excludes>
            x0Assertion/oasisNamesTcSAML1/**,org/w3/x2000/x09/**
        </spring-javaformat.excludes>
    </properties>
```

Hope, this helps somebody. It would be great, if you put it also in your Readme!
