### ISSUE TITLE
document hw to fix the Gradle task inter-dependency issues you'll get if you use Gradle.

### ISSUE THREAD

**Issue by joshlong** [spring-io/spring-javaformat#407]
Im applying this to a codebase with Java 21 and Spring Boot 3.2.3 and it complains about missing dependency ordering if you just add the stanza suggested in the `README.md`.

But, if you add this to the end of the `build.gradlew`, it fixes things. Maybe there's a better way. I don't know.. But it took me some puzzling to figure this out.

```groovy

tasks.named('compileJava') {
    it.dependsOn ':formatMain'
}

tasks.named('compileTestJava') {
    it.dependsOn ':formatTest'
}

```

**Comment by wilkinsona** [comment]
We should fix this in the plugin rather than working around it with documentation.

Which version of Gradle are you using, @joshlong?

**Comment by joshlong** [comment]
It's compatible with Java 21. But I'm afk at the moment. But it's among the newer ones that finally support Java 21

**Comment by wilkinsona** [comment]
I wonder if you ran `format` and some other tasks at the same time, perhaps `./gradlew format build` or something like that?

**Comment by wilkinsona** [comment]
Closing due to the lack of requested feedback.
