### ISSUE TITLE
line wrap at 90 chars, instead of 120

### ISSUE THREAD

**Issue by RZXQ** [spring-io/spring-javaformat#427]
The source formatter uses 120 chars for wrapping. This aims to strike a balance between making use of available horizontal space in your IDE and avoiding unwanted additional wrapping when viewing code on GitHub and the like.

but it seems in both intellij and vscode, the line breaks at 90 chars

**Comment by wilkinsona** [comment]
It was a conscious decision to [move from 90 chars to 120](https://github.com/spring-io/spring-javaformat/issues/100) and it's unlikely that we'll drop back to 90 again.

> but it seems in both intellij and vscode, the line breaks at 90 chars

When configured to use this formatter, both IntelliJ and vscode should honor its 120 char line width. Is that not what you're seeing?

**Comment by RZXQ** [comment]
I'm afraid not, the line indeed breaks at col 90, I'm using IntelliJ along with the formatter for a Java project, not using Maven or Gradle

**Comment by wilkinsona** [comment]
Given that you're not using Maven or Gradle, do you have the `.springjavaformatconfig` file that is [required to activate the formatter](https://github.com/spring-io/spring-javaformat?tab=readme-ov-file#intellij-idea)? The status bar should indicate if the formatter's active.

If you believe that the required file's in place but the formatter's not active, or the formatter's active but it's not formatting the code as expected, please share a minimal IntelliJ project the reproduces the problem and we can take a look.

**Comment by RZXQ** [comment]
![CleanShot 2024-11-10 at 00 20 05@2x](https://github.com/user-attachments/assets/997d691f-eef7-4bc4-aa22-4c7af52cd1b7)
![CleanShot 2024-11-10 at 00 12 06@2x](https://github.com/user-attachments/assets/acf1f675-8d26-4035-89ae-148d39a22c97)

**Comment by philwebb** [comment]
We still wrap javadoc and comments at 90 chars (see [this part of the config](https://github.com/spring-io/spring-javaformat/blob/bbd8fa95abe07c2cf998443a0cb56dc12563d092/spring-javaformat/spring-javaformat-formatter/src/main/resources/io/spring/javaformat/formatter/eclipse/formatter.prefs#L84)). This was an intentional choice since we thought it would be useful to still have readable javadoc on smaller screens. I'm not totally sure that we should change it at this point, although it is a little inconsistent with the code wrapping.

**Comment by RZXQ** [comment]
Thanks

**Comment by andreasevers** [comment]
@philwebb is it possible to overwrite this setting in IntelliJ to align with the 120 chars?

**Comment by philwebb** [comment]
@andreasevers, only by forking the project I'm afraid. We're intentionally trying to limit the configuration options we support. From the README:

> Since the aim of this project is to provide consistency, each plugin is not generally configurable. You need to change your code to match the required conventions. You can’t configure the plugin conventions to match your style!
