### ISSUE TITLE
Incorrect format try-with-resources

### ISSUE THREAD

**Issue by eddumelendez** [spring-io/spring-javaformat#429]
Declaring multiple resources and applying the spring-javaformat maven plugin results in

https://github.com/eddumelendez/testcontainers-samples/blob/47eae35b555b8ff597b4c062d4e0b1819f630a6e/spring-boot-hazelcast/src/test/java/com/example/springboothazelcast/SpringBootHazelcastApplicationTest.java#L51-L53

```java
try (SqlResult mappingResult = sql.execute(mapping);
		SqlResult insertResult = sql.execute(insert);
		SqlResult sqlResult = sql.execute("SELECT cities FROM cities")) {
```

Expected:

```java
try (SqlResult mappingResult = sql.execute(mapping);
     SqlResult insertResult = sql.execute(insert);
     SqlResult sqlResult = sql.execute("SELECT cities FROM cities")) {
```

I also noticed some code in spring-boot where instead of declaring multiple resources a nested try-with-resources was used instead.

**Comment by wilkinsona** [comment]
@eddumelendez, I've edited your comment to include the actual result. Is it the indentation that's the problem with both `insertResult` and `sqlResult` being indented further than you'd like?

**Comment by wilkinsona** [comment]
Setting `org.eclipse.jdt.core.formatter.alignment_for_resources_in_try=` to `85` should result in this (using spaces to simulate a tab-width of 4):

```java
try (SqlResult mappingResult = sql.execute(mapping);
    SqlResult insertResult = sql.execute(insert);
    SqlResult sqlResult = sql.execute("SELECT cities FROM cities")) {
}
```

It's not exactly as expected as that would require using spaces to get column alignment which I don't think we should do.

**Comment by philwebb** [comment]
I think I prefer the existing formatting. I'm not a fan of alignment using spaces.

**Comment by wilkinsona** [comment]
We only need to use spaces if we want exact column alignment. https://github.com/spring-io/spring-javaformat/issues/429#issuecomment-2514115519 is using tabs, just fewer of them so that the `insertResult` and `sqlResult` lines are less indented. Maybe this is a bit more clear:

Current
```java
try (SqlResult mappingResult = sql.execute(mapping);
\t\tSqlResult insertResult = sql.execute(insert);
\t\tSqlResult sqlResult = sql.execute("SELECT cities FROM cities")) {
}
```

Proposed
```java
try (SqlResult mappingResult = sql.execute(mapping);
\tSqlResult insertResult = sql.execute(insert);
\tSqlResult sqlResult = sql.execute("SELECT cities FROM cities")) {
}
```

FWIW, I prefer the proposed formatting although I wouldn't call either of them incorrect. It's quite subjective.

**Comment by philwebb** [comment]
I think I still prefer the existing one because it doesn't align things with the code that's following:

e.g.:

```java
try (SqlResult mappingResult = sql.execute(mapping);
		SqlResult insertResult = sql.execute(insert);
		SqlResult sqlResult = sql.execute("SELECT cities FROM cities")) {
	mappingResult.foo();
}
```

seems easier to read to me than


```java
try (SqlResult mappingResult = sql.execute(mapping);
	SqlResult insertResult = sql.execute(insert);
	SqlResult sqlResult = sql.execute("SELECT cities FROM cities")) {
	mappingResult.foo();
}
```

**Comment by wilkinsona** [comment]
Good point. I'd overlooked that by reducing the examples down too far. I too now prefer the existing indentation.

**Comment by eddumelendez** [comment]
Thanks for sharing. I think it works as expected, initially though it was a bug 😅 feel free to close the issue :)
