### ISSUE TITLE
how to complitely disable it

### ISSUE THREAD

**Issue by mtbadi39** [spring-io/spring-javaformat#43]
```
<checkstyle.skip>true</checkstyle.skip>
<skip.it>true</skip.it>
```
Not working !

**Comment by philwebb** [comment]
Skipping checkstyle entirely is done by the checkstyle plugin, not the rules defined in this project. See [the skip](https://maven.apache.org/plugins/maven-checkstyle-plugin/check-mojo.html#skip) attribute for Maven.

**Comment by mtbadi39** [comment]
`<disable.checks>true</disable.checks>` property from **spring-boot-parent pom** worked for me. Sorry !
