### ISSUE TITLE
Switch to jetbrains release repo

### ISSUE THREAD

**Issue by philwebb** [spring-io/spring-javaformat#61]
https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/182.3684.101/ideaIC-182.3684.101.zip

**Comment by MALPI** [comment]
I guess the ticket is about hosting the plugin in the intellij repo? In the meantime it would be great to extend documentation how to install the plugin in intellij. Currently I am clueless where to put the jar that I download from spring.io.

**Comment by wilkinsona** [comment]
> I guess the ticket is about hosting the plugin in the intellij repo? 

No, it's a task to change where the plugin's build downloads the IDEA binary from.

> In the meantime it would be great to extend documentation how to install the plugin in intellij

The IDEA [documentation](https://www.jetbrains.com/help/idea/managing-plugins.html) describes how to install a plugin from disk:

> ### Install plugin from disk
> 1. In the **Settings/Preferences** dialog (⌘,), select **Plugins**.
> 2. In the **Plugins** dialog, click the cogwheel icon and then click **Install Plugin from Disk**.
> 3. Select the plugin archive file and click **OK**.
> 4. Click **OK** to apply the changes and restart the IDE if prompted.

**Comment by MALPI** [comment]
Ok, sorry for spamming the wrong ticket then. Still, when I download the files from spring.io and create a zip file out of the files, since zip file is the only format that "Install Plugin from Disk" supports. When then trying to import Intellij shows error that it's Failing to load a plugin descriptor.

**Comment by snicoll** [comment]
There's no archive to create, just use this file http://repo.spring.io/release/io/spring/javaformat/spring-javaformat-intellij-plugin/0.0.6/spring-javaformat-intellij-plugin-0.0.6.jar

**Comment by MALPI** [comment]
Sorry but same error.

**Comment by wilkinsona** [comment]
It works for me with 2018.2.5.

**Comment by MALPI** [comment]
Donwloaded the file again and now it worked magically. Thanks a lot for your support.
