### ISSUE TITLE
Document how to turn off spring-javaformat-maven-plugin in one maven module in multi-module maven project

### ISSUE THREAD

**Issue by rajadilipkolli** [spring-io/spring-javaformat#63]

**Comment by wilkinsona** [comment]
As with most Maven plugins, there's a `skip` property that can be used:

```
<configuration>
    <skip>true</skip>
</configuration>
```

Given that this is a Maven convention, I'm not sure that it warrants a special mention in the README. If you disagree, please feel free to contribute a change for consideration.
