### ISSUE TITLE
Consider providing more granular Spring checks

### ISSUE THREAD

**Issue by vpavic** [spring-io/spring-javaformat#69]
Currently, [`spring-checkstyle.xml`](https://github.com/spring-io/spring-javaformat/blob/master/spring-javaformat/spring-javaformat-checkstyle/src/main/resources/io/spring/javaformat/checkstyle/spring-checkstyle.xml) that `SpringChecks` loads defines quite a few checks. For existing projects looking to adopt `spring-javaformat` this can be a big obstacle.

It would be nice if this project provided more granular Spring checks - for example, since `spring-checkstyle.xml` already groups checks internally by their type (i.e. _Annotations_, _Block Checks_, etc.) it would be nice if those were actually check groups that could be used individually by extracting them into `SpringAnnotationChecks`, `SpringBlockChecks`, etc.

This would also make the project more reusable generally.

**Comment by philwebb** [comment]
I know the migrating those checkstyle rules can be quite a pain, but I'm keen to try and persuade people to use them in their entirety if at all possible. The primary goal of those rules is to bring consistency, so making it easy to opt-out really goes against that aim.

I'm also not sure how it would be practically possible to group the rules in such a way that would make everyone happy. I have considered in the past, but in the end I decided that copy-paste of the `spring-checkstyle.xml` and remove what you don't want was the best option.

**Comment by vpavic** [comment]
Thanks for the feedback.
