### ISSUE TITLE
Allow SpringHeaderCheck to load custom files

### ISSUE THREAD

**Issue by vpavic** [spring-io/spring-javaformat#70]
Currently, `SpringHeaderCheck` loads header file from the same package:

https://github.com/spring-io/spring-javaformat/blob/1830776220d0fc89456d947d24d8ca346118a0b9/spring-javaformat/spring-javaformat-checkstyle/src/main/java/io/spring/javaformat/checkstyle/check/SpringHeaderCheck.java#L146-L147

Unless I'm missing something, this makes it difficult to use a custom header as it requires users to place the custom header in `io/spring/javaformat/checkstyle/check` package on their Checkstyle classpath. It would be nice if `SpringHeaderCheck` would load the custom header from the root of Checkstyle classpath.

To clarify, assuming a Gradle build with default Checkstyle config location of `config/checkstyle` one need to do the following:

```gradle
checkstyle {
    toolVersion = '8.12'
    // other config...
}

tasks.withType(Checkstyle) {
    checkstyleClasspath += files('config/checkstyle')
}
```

And then place the custom header file in `config/checkstyle/io/spring/javaformat/checkstyle/check` while the desirable would be to simply place it in `config/checkstyle`.

**Comment by philwebb** [comment]
Good idea!

**Comment by philwebb** [comment]
Actually, on review the file isn't really designed to be replaced in that way. It's working by accident currently. I think it would be better if you could specify an external file directly and we ignore the `type` attribute.
