### ISSUE TITLE
Eclipse Update Site hasn't been updated since 0.0.5

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/spring-javaformat#73]
I'm not sufficiently familiar with how an Eclipse update site works to know if this is the cause of the problem, but I have noticed that the `content.xml` file that's in the site's `content.jar` file does not contain an entry for 0.0.6.

**Comment by philwebb** [comment]
Since 0.0.7 has been released I guess we can just close this one.

**Comment by wilkinsona** [comment]
Unfortunately 0.0.7 isn't offered either.

**Comment by philwebb** [comment]
0.0.7 never made it, I guess the publish failed. 0.0.8 and 0.0.6 are available. I think the `publish-eclipse-update-site` CI task was just run too soon and the list of versions didn't get reported correctly from Bintray.
