### ISSUE TITLE
Document that formatter does not order imports

### ISSUE THREAD

**Issue by ttddyy** [spring-io/spring-javaformat#77]
Should this plugin re-order import statements?

In spring-boot project, 

This is the one passing `./mvnw validate`

```
import java.time.Duration;
import java.util.Collections;
import java.util.Set;

import org.junit.Test;
import org.mockito.InOrder;

import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.TransactionDefinition;
import org.springframework.transaction.annotation.Isolation;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.support.TransactionTemplate;
```

I swapped `java.time.Duration` and `java.util.Collections`, then ran `./mvnw io.spring.javaformat:spring-javaformat-maven-plugin:apply`

Nothing changed in import ordering, and `./mvnw validate` failes on checkstyle.

Also, on Intellij with spring-javaformat plugin, when I do "Optimise Import", it shuffles import like this:

```
import org.junit.Test;
import org.mockito.InOrder;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.TransactionDefinition;
import org.springframework.transaction.annotation.Isolation;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.support.TransactionTemplate;

import java.time.Duration;
import java.util.Collections;
import java.util.Set;
```
This also fails on checkstyle.

**Comment by ttddyy** [comment]
Ok, thanks,

@philwebb 
Can you add this limitation (or area that this plugin applies) to maybe README.adoc?

**Comment by philwebb** [comment]
Sure

**Comment by jasonparallel** [comment]
Is the recommendation to setup your IDE so that it auto organizes imports following this projects rules? (As mentioned here https://github.com/checkstyle/checkstyle/issues/1448)

**Comment by philwebb** [comment]
@jasonparallel If you're using eclipse then the plugin will apply project specific settings that will do that. If you're using IntelliJ you need to configure things yourself. The checkstyle order we expect is defined in [SpringImportOrderCheck.java](https://github.com/spring-io/spring-javaformat/blob/master/spring-javaformat/spring-javaformat-checkstyle/src/main/java/io/spring/javaformat/checkstyle/check/SpringImportOrderCheck.java)
