### ISSUE TITLE
Annotation attributes are not being wrapped

### ISSUE THREAD

**Issue by OlgaMaciaszek** [spring-io/spring-javaformat#78]
After running the formatter plugin, the following code (with new line after comma):
```java
@SpringBootTest(classes = RibbonClientConfigurationIntegrationTests.TestLBConfig.class,
		properties = "test.ribbon.ServerListRefreshInterval=999")
```
will be converted to (with no new line):
```java
@SpringBootTest(classes = RibbonClientConfigurationIntegrationTests.TestLBConfig.class, properties = "test.ribbon.ServerListRefreshInterval=999")
```

This is problematic, taken into account that we usually want to stick to a certain line length limit.

**Comment by philwebb** [comment]
It looks like the underlying Eclipse formatter can wrap annotations so we probably just need to change an option in https://github.com/spring-io/spring-javaformat/blob/master/spring-javaformat/spring-javaformat-formatter/src/main/resources/io/spring/javaformat/formatter/formatter.prefs

![screen shot 2019-02-07 at 10 30 53 am](https://user-images.githubusercontent.com/519772/52434169-9945f980-2ac3-11e9-8fe1-94f828f8d3ee.png)
