### ISSUE TITLE
Exclude folder from being checked

### ISSUE THREAD

**Issue by MALPI** [spring-io/spring-javaformat#80]
Hey there,

I have a folder `generated-sources` in my sourceset. Currently the task `checkFormat` fails when validating the folder. When checking the code, I didn't find a way to exclude sourcesets from the `check` task?

Any idea?

It's running with gradle.

**Comment by MALPI** [comment]
Achieved it now with a small workaround:

```
tasks.withType(SourceTask) {
    exclude "package/to/exclude"
}
```

**Comment by MALPI** [comment]
@snicoll @wilkinsona @philwebb any idea how to achieve this?

**Comment by wilkinsona** [comment]
It should work if you apply the exclusion more precisely. Something like this:

```groovy
tasks.withType(io.spring.javaformat.gradle.CheckTask) {
    exclude "package/to/exclude"
}
```

**Comment by MALPI** [comment]
Yeah, this seems to work. Thanks a lot @wilkinsona. I will file a PR for the docs later.

**Comment by wilkinsona** [comment]
Cool. Thanks!
