### ISSUE TITLE
Add Eclipse Checkstyle Plugin support

### ISSUE THREAD

**Issue by brenuart** [spring-io/spring-javaformat#82]
Sorry for posting this issue here but I could not find any other place :(

I tried to use the `spring-javaformat-checkstyle` together with the `maven-checkstyle-plugin` as described in the project home page. I made a simple project with no dependencies and a simple main class. I copied the `maven-checkstyle-plugin` section from the readme and pasted it into the project pom. I did not include the `spring-javaformat-maven-plugin` plugin. The pom is as follows:
```
<project>
	....
	<dependencies>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-checkstyle-plugin</artifactId>
				<version>3.0.0</version>
				<dependencies>
					<dependency>
						<groupId>com.puppycrawl.tools</groupId>
						<artifactId>checkstyle</artifactId>
						<version>8.11</version>
					</dependency>
					<dependency>
						<groupId>io.spring.javaformat</groupId>
						<artifactId>spring-javaformat-checkstyle</artifactId>
						<version>0.0.6</version>
					</dependency>
				</dependencies>
				<executions>
					<execution>
						<id>checkstyle-validation</id>
						<phase>validate</phase>
						<inherited>true</inherited>
						<configuration>
							<configLocation>io/spring/javaformat/checkstyle/checkstyle.xml</configLocation>
							<includeTestSourceDirectory>true</includeTestSourceDirectory>
						</configuration>
						<goals>
							<goal>check</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
```

Everything works fine from the command line: `mvn validate` triggers the validation and reports violations.

Unfortunately, things are different from within Eclipse where I constantly receive an error saying:
```
Checkstyle execution failed due to an internal error. Please check the error log for details.
```
My Eclipse installation is running _Eclipse Checkstyle Plugin_ version `8.12.0` (it installed itself automatically after the project is imported inside Eclipse - I did not select the version myself). `spring-javaformat-checkstyle` is built against `8.11.0` - is this an issue?

I tested with different versions of Eclipse, every time with a fresh installation and a brand new workspace - no other plugins than what is included in the _Eclipse IDE for Java Developers_ package. I tested with Eclipse Photon, 201809 and 201812 and got the same error each time.

The Eclipse log contains the following when the error occurs:
```
!ENTRY net.sf.eclipsecs.core 4 0 2019-03-13 19:35:51.442
!MESSAGE Checkstyle-Plugin: cannot initialize module io.spring.javaformat.checkstyle.SpringChecks - Unable to instantiate 'io.spring.javaformat.checkstyle.SpringChecks' class, it is also not possible to instantiate it as null. Please recheck that class name is specified as canonical name or read how to configure short name usage http://checkstyle.sourceforge.net/config.html#Packages. Please also recheck that provided ClassLoader to Checker is configured correctly.
!STACK 0
com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module io.spring.javaformat.checkstyle.SpringChecks - Unable to instantiate 'io.spring.javaformat.checkstyle.SpringChecks' class, it is also not possible to instantiate it as null. Please recheck that class name is specified as canonical name or read how to configure short name usage http://checkstyle.sourceforge.net/config.html#Packages. Please also recheck that provided ClassLoader to Checker is configured correctly.
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:460)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:198)
	at net.sf.eclipsecs.core.builder.CheckerFactory.createCheckerInternal(CheckerFactory.java:299)
	at net.sf.eclipsecs.core.builder.CheckerFactory.createChecker(CheckerFactory.java:133)
	at net.sf.eclipsecs.core.builder.Auditor.runAudit(Auditor.java:141)
	at net.sf.eclipsecs.core.builder.CheckstyleBuilder.handleBuildSelection(CheckstyleBuilder.java:306)
	at net.sf.eclipsecs.core.jobs.RunCheckstyleOnFilesJob.runInWorkspace(RunCheckstyleOnFilesJob.java:119)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to instantiate 'io.spring.javaformat.checkstyle.SpringChecks' class, it is also not possible to instantiate it as null. Please recheck that class name is specified as canonical name or read how to configure short name usage http://checkstyle.sourceforge.net/config.html#Packages. Please also recheck that provided ClassLoader to Checker is configured correctly.
	at com.puppycrawl.tools.checkstyle.PackageObjectFactory.createModule(PackageObjectFactory.java:208)
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:450)
	... 8 more
```

I have no idea what I did wrong :-(
Can someone help me ?
Thanks for your help.

**Comment by snicoll** [comment]
> I made a simple project with no dependencies and a simple main class. 
@brenuart rather than pasting code in text we have to parse, could you please attach that small project that reproduces the error you're experiencing? If we can run it, it's far more easier than trying to put the pieces based on your description.

**Comment by brenuart** [comment]
Please find two ZIPs with the following content:

- [checkstyle.zip](https://github.com/spring-io/spring-javaformat/files/2965482/checkstyle.zip) Contains the sample project 
- [eclipse-workspace.zip](https://github.com/spring-io/spring-javaformat/files/2965487/eclipse-workspace.zip) The eclipse workspace after the project is imported (contains the eclipse log for troubleshooting). Not sure you can reuse the workspace asis on your own workstation tho...

The scenario to reproduce is as follows:
1. download and install _Eclipse 201812_, package _Eclipse IDE for Java Developers_
2. start Eclipse and install the checkstyle M2E plugin from Preferences|Maven|Discovery
3. restart Eclipse
4. import the project as _existing maven project_

The error appears in the _Problems_ view after import.

**Comment by brenuart** [comment]
@snicoll I know you are busy atm - but did you have a chance to have a look at the sample I provided earlier?

**Comment by wilkinsona** [comment]
Thanks for the sample, @brenuart. Using the custom checks with Eclipse isn't supported at the moment. I believe we need to make the custom checks available to the Eclipse Checkstyle Plugin by [declaring an extension](https://checkstyle.org/eclipse-cs/#!/custom-checks).

**Comment by brenuart** [comment]
Ok - so the only Eclipse integration is for the formatter? I missed that when reading the doc :(
